import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, ChevronLeft, ChevronRight, Mail, MapPin, Menu, Phone, Play, X} from 'lucide-react';
import './styles.css';

const services = [
  {title:'Speaking & Teaching Engagements', short:'ST', text:'Engaging talks, workshops, and learning experiences that make complex technology practical, relevant, and actionable.', points:['Keynotes & panels','Interactive workshops','Corporate & academic teaching']},
  {title:'Fractional CTO Services', short:'CTO', text:'Executive technology leadership for organizations that need experienced direction without a full-time technology officer.', points:['Technology strategy','Architecture & vendor guidance','Team and delivery leadership']},
  {title:'AI Consulting & Security Services', short:'AI', text:'Responsible AI adoption and security guidance designed around real business needs, risks, and opportunities.', points:['AI opportunity assessment','Secure implementation planning','Governance & risk strategy']}
];

const media = [
  {id:'MDj6za6XUSg', title:'Working in Tech Ep 43 — How to Become a Technical Consultant with Jonathan Exume', channel:'JuwonTheTechie'},
  {id:'ZW9y3luzpgI', title:'RIDE Con featuring Shakiri Murrain, Jonathan Exume, and Guy Mills', channel:'Rolling Out'},
  {id:'7XL7Bdqu1k4', title:'AI Secrets Revealed: Insights from a Tech Leader', channel:'Rachel Mlota'},
  {id:'LlWTlID6vN4', title:'ToC Presents: Get To Know — Diamonde Henderson', channel:'Technologists of Color'},
  {id:'3277JBfsneo', title:'Data Engineer Aces Meta Mock Interview featuring Jonathan Exume', channel:'BeforeTheBillions'},
  {id:'RIbO_WAZ7Fs', title:'Diversitech Talk with Jonathan Exume', channel:'The Mentor Mogul'},
  {id:'YucjBM8jwLo', title:'HBCU AI for Business Masterclass — Session 1 with Jonathan Exume', channel:'Howard University PNC Bank Regional Center at CAU'}
];

function Brand({footer=false}){return <a className={`brand ${footer?'brand--footer':''}`} href="#home" aria-label="Exumatron home"><img src="/exumatron-lion.png" alt=""/><span>Exumatron <b>LLC</b></span></a>}
function Header(){const [open,setOpen]=useState(false); useEffect(()=>{const close=()=>setOpen(false); window.addEventListener('hashchange',close); return()=>window.removeEventListener('hashchange',close)},[]); return <header><Brand/><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{['Home','About','Services','Media','Contact'].map(n=><a key={n} href={`#${n.toLowerCase()}`} onClick={()=>setOpen(false)}>{n}</a>)}<a className="nav-cta" href="#contact" onClick={()=>setOpen(false)}>Start a conversation</a></nav></header>}

function Hero(){return <section className="hero" id="home"><div className="hero-bg"/><div className="hero-copy"><h1>Technology with the courage to <span>move forward.</span></h1><p>Exumatron turns ambitious ideas into practical digital experiences, intelligent systems, and modern technology solutions.</p><div className="actions"><a className="button primary" href="#contact">Start a conversation <ArrowRight/></a><a className="button ghost" href="#services">Explore our capabilities</a></div></div><a className="scroll-cue" href="#about"><span>Scroll to explore</span><i/></a></section>}

function About(){return <section className="about section" id="about"><div className="lion-wrap portrait-wrap"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><img src="/exumatron-founder-cartoon.png" alt="Cartoon portrait of the Exumatron founder"/></div><div className="about-copy"><p className="section-index">01 — About</p><h2>Built for what’s next.</h2><p className="lead">Technology should create momentum—not more complexity.</p><p>Exumatron LLC partners with ambitious teams to shape thoughtful digital experiences and modern systems. We combine strategy, engineering, and creative execution to move from possibility to something practical, resilient, and distinctly yours.</p><p>Our approach is direct: listen closely, design deliberately, and build with the future in view.</p><a className="text-link" href="#contact">Tell us what you’re building <ArrowRight/></a></div></section>}

function Services(){const [active,setActive]=useState(0); const rotate=d=>setActive((active+d+services.length)%services.length); return <section className="services section" id="services"><div className="section-heading"><p className="section-index">02 — Services</p><h2>Explore what we can<br/>build together.</h2><p>Select a capability to see how Exumatron can move your next idea forward.</p></div><div className="service-explorer"><div className="service-orbits" aria-hidden="true"><i/><i/><i/></div><button className="round prev" onClick={()=>rotate(-1)} aria-label="Previous service"><ChevronLeft/></button><div className="service-core"><div className="core-ring"><span>{services[active].short}</span></div><small>Selected capability</small><h3>{services[active].title}</h3></div><button className="round next" onClick={()=>rotate(1)} aria-label="Next service"><ChevronRight/></button><div className="service-detail" key={active}><p>{services[active].text}</p><ul>{services[active].points.map(p=><li key={p}>{p}</li>)}</ul><a href="#contact">Discuss this capability <ArrowRight/></a></div><div className="service-tabs">{services.map((s,i)=><button className={i===active?'active':''} onClick={()=>setActive(i)} key={s.title}><span>0{i+1}</span>{s.title}</button>)}</div></div><p className="services-note">A richer, custom service experience is ready for the content you’ll provide next.</p></section>}

function Media(){const [start,setStart]=useState(0);const [selected,setSelected]=useState(null);const visible=[0,1,2].map(offset=>(start+offset)%media.length);useEffect(()=>{if(selected===null)return;const close=e=>{if(e.key==='Escape')setSelected(null)};document.body.classList.add('modal-open');window.addEventListener('keydown',close);return()=>{document.body.classList.remove('modal-open');window.removeEventListener('keydown',close)}},[selected]);const video=selected===null?null:media[selected];return <section className="compact-media section" id="media"><div className="compact-media-head"><div><p className="section-index">03 — Media</p><h2>Conversations in motion.</h2></div><p>Interviews, panels, and practical conversations about technology, leadership, AI, and building what comes next.</p></div><div className="compact-carousel"><button className="carousel-arrow left" onClick={()=>setStart((start-1+media.length)%media.length)} aria-label="Previous interviews"><ChevronLeft/></button><div className="compact-grid">{visible.map(i=>{const item=media[i];return <article className="video-card" key={item.id}><button className="card-poster" onClick={()=>setSelected(i)} aria-label={`Play ${item.title}`}><img loading="lazy" src={`https://i.ytimg.com/vi/${item.id}/mqdefault.jpg`} alt=""/><span><Play fill="currentColor"/></span></button><div><small>{item.channel}</small><h3>{item.title}</h3><button className="card-watch" onClick={()=>setSelected(i)}>Watch video <ArrowRight/></button></div></article>})}</div><button className="carousel-arrow right" onClick={()=>setStart((start+1)%media.length)} aria-label="Next interviews"><ChevronRight/></button></div><div className="carousel-status"><span>{String(start+1).padStart(2,'0')} / {String(media.length).padStart(2,'0')}</span><div>{media.map((item,i)=><button key={item.id} className={i===start?'active':''} onClick={()=>setStart(i)} aria-label={`Show interview ${i+1}`}/>)}</div></div>{video?<div className="video-modal" role="dialog" aria-modal="true" aria-label={video.title} onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="modal-panel"><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close video"><X/></button><div className="modal-player"><iframe src={`https://www.youtube.com/embed/${video.id}?autoplay=1&rel=0`} title={video.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/></div><div className="modal-meta"><span>{video.channel}</span><h3>{video.title}</h3></div></div></div>:null}</section>}

function Contact(){const [sent,setSent]=useState(false); return <section className="contact section" id="contact"><div><p className="section-index">04 — Contact</p><h2>Let’s build the<br/><span>next move.</span></h2><p>Have a project, a challenge, or simply the beginning of an idea? We’d like to hear it.</p><div className="contact-lines"><a href="mailto:jon@exumatron.co.technology"><Mail/>jon@exumatron.co.technology</a><a href="tel:+16787431526"><Phone/>+1 678 743 1526</a><span><MapPin/>Austell, Georgia</span></div></div>{sent?<div className="success"><span>Message received</span><h3>Thanks for reaching out.</h3><p>Your note is ready for delivery. We’ll be in touch soon.</p><button className="button ghost" onClick={()=>setSent(false)}>Send another</button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Name<input required name="name" autoComplete="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" autoComplete="email" placeholder="you@company.com"/></label><label>Tell us about your project<textarea required name="message" rows="4" placeholder="What are you hoping to build?"/></label><button className="button primary" type="submit">Send your message <ArrowRight/></button></form>}</section>}

function Footer(){return <footer><Brand footer/><p>Technology with the courage to move forward.</p><div><a href="#about">About</a><a href="#services">Services</a><a href="#media">Media</a><a href="#contact">Contact</a></div><small>© {new Date().getFullYear()} Exumatron LLC. All rights reserved.</small></footer>}
function App(){return <><Header/><main><Hero/><About/><Services/><Media/><Contact/></main><Footer/></>}

createRoot(document.getElementById('root')).render(<App/>);
